version: '3'

services:
  grafana:
    image: quay.io/pngmbh/quantum-grafana:latest
    labels:
      traefik.enable: "true"
      traefik.docker.network: "public"
      traefik.port: "3000"
      traefik.frontend.rule: Host:grafana.your-endpoint-or-cluster.docker.planetary-networks.de
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - public
    environment:
      INITIAL_ADMIN_PASSWORD: change-me-change-me
      QUANTUM_ENDPOINT: your-endpoint-or-cluster-name

volumes:
  grafana-storage:

networks:
  public:
    external: true
