---
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3 
        with:
          registry: r.planetary-quantum.com
          username: ${{ secrets.QUANTUM_REGISTRY_USER }}
          password: ${{ secrets.QUANTUM_REGISTRY_PASSWORD }}
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: r.planetary-quantum.com/quantum-public/grafana:pre
      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
